---
title: "05 TV-Duelle / Kandidaten"
format:
  html:
    code-fold: true
    message: false
    warning: false
---

```{r setup}
library(tidyverse)
library(ggtext)
library(here)

knitr::opts_chunk$set(dev = "ragg_png")

source(here("R", "custom-theme.R"))
theme_set(theme_custom())
```

## Daten

Aufbereitung der Daten in [05-poba-kandidaten.R](05-poba-kandidaten.R)

```{r load-data}
df_skalo <- read_tsv(here("data", "Politbarometer", "politbarometer-kandidaten.tsv"))
```

## Visualisierung

```{r plot-skalo-1}
df_skalo |> 
  mutate(wahl = factor(wahl)) |> 
  ggplot(aes(wahl, bewertung, fill = partei)) +
  geom_vline(
    aes(xintercept = wahl), 
    linewidth = 3, color = "grey80") +
  geom_hline(aes(yintercept = 0), linewidth = 0.5) +
  geom_point(
    aes(
      shape = ifelse(kandidat == "Merkel" & wahl == "2021", 4, 21),
      col = ifelse(kandidat == "Merkel" & wahl == "2021", "black", "white")),
    size = 3) +
  geom_text(
    aes(label = kandidat),
    family = "Roboto Condensed", size = 2, hjust = 0, nudge_x = 0.15
  ) +
  scale_x_discrete(position = "top") +
  scale_y_continuous(labels = scales::label_number(style_positive = "plus")) +
  scale_fill_manual(values = party_pal) +
  scale_shape_identity() +
  scale_color_identity() +
  coord_cartesian(ylim = c(-1, 3)) +
  guides(fill = "none") +
  labs(
    x = NULL, y = "Bewertung"
  )
```

```{r plot-skalo-2, fig.width = 7.5, fig.height=6}

annotation_size <- 4.5

df_skalo |> 
  mutate(wahl_fct = factor(wahl)) |> 
  ggplot(aes(wahl_fct, bewertung, fill = partei)) +
  geom_vline(
    aes(xintercept = wahl_fct), 
    linewidth = 9, color = alpha("grey80", 0.3)) +
  geom_hline(aes(yintercept = 0), linewidth = 0.5) +
  geom_line(
    aes(group = kandidat),
    linetype = "dashed", linewidth = 0.3, col = "grey50"
  ) +
  geom_point(
    aes(
      shape = ifelse(kandidat == "Merkel" & wahl == "2021", 4, 21),
      col = ifelse(kandidat == "Merkel" & wahl == "2021", "black", "white")),
    size = annotation_size) +
  geom_text(
    data = ~filter(.,
                   wahl %in% c(2005, 2021) & kandidat == "Merkel" |
                   wahl == 1980 |
                   wahl == 1983 & kandidat == "Kohl" |
                   wahl == 1998 & kandidat == "Schröder" |
                   kandidat == "Scholz" |
                   kandidat == "Habeck" |
                   kandidat == "Merz"
                   ),
    aes(label = kandidat),
    family = "Roboto Condensed", size = annotation_size, hjust = 0, nudge_x = 0.2
  ) +
  annotate(
    "richtext",
    x = c("1987", "2021", "2025"), 
    y = c(0.38, -0.55, 0.5), 
    label = c(
      "Kohl war bislang<br>der **unbeliebteste<br>erfolgreiche**<br>Kanzlerkandidat",
      "Laschet",
      "**Alle**<br>Kandidaten<br>im Schnitt<br>**negativ**<br>bewertet"),
    vjust = c(1, 0.5, 0.5),
    hjust = c(0, 1, 0),
    fill = NA, label.size = 0, family = "Roboto Condensed", size = annotation_size,
    lineheight = 1
  ) +
  annotate(
    GeomCurve,
    x = c("1987"),
    xend = c("1987"),
    y = c(0.33),
    yend = c(0.6),
    curvature = -0.3, linewidth = 0.2
  ) +
  scale_x_discrete(position = "top") +
  scale_y_continuous(labels = scales::label_number(style_positive = "plus")) +
  scale_fill_manual(values = party_pal) +
  scale_shape_identity() +
  scale_color_identity() +
  coord_cartesian(ylim = c(-1, 3), clip = "off") +
  guides(fill = "none") +
  labs(
    title = "Erstmals sämtliche Kanzlerkandidaten im Schnitt negativ bewertet",
    subtitle = "Bewertung der Kandidat:innen in der jeweils letzten Politbarometer-Erhebung vor der Bundestagswahl auf einer Skala von -5 bis +5 (2025: Politbarometer Februar II)",
    caption = "Daten: Politbarometer (via GESIS & forschungsgruppe.de).
    Visualisierung: Ansgar Wolsing & Thorsten Faas",
    x = NULL, y = NULL # "Bewertung"
  ) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.x.top = element_text(family = "Roboto Condensed SemiBold"),
    plot.subtitle = element_textbox(margin = margin(b = 20)),
    plot.margin = margin(t = 4, r = 40, b = 4, l = 4)
  )
```

##### Variante mit vollständigen Kandidatennennung in Fußnote

```{r plot-skalo-3, fig.width = 7.5, fig.height=7}
annotation_size <- 4.25

kandidaten_hinweis <- df_skalo |> 
  filter(!kandidat %in% c("Merkel", "Schröder", "Schmidt", "Kohl", "Merz", "Scholz", 
                          "Baerbock", "Habeck", "Laschet", "Strauß")) |> 
  transmute(wahl_kandidat_label = paste(wahl, kandidat, sep = " "))

df_skalo |> 
  filter(!(wahl == 2021 & kandidat == "Merkel")) |> 
  mutate(wahl_fct = factor(wahl)) |> 
  ggplot(aes(wahl_fct, bewertung, fill = partei)) +
  geom_vline(
    aes(xintercept = wahl_fct), 
    linewidth = 9, color = alpha("grey80", 0.3)) +
  geom_hline(aes(yintercept = 0), linewidth = 0.5) +
  geom_line(
    aes(group = kandidat),
    linetype = "dashed", linewidth = 0.3, col = "grey50"
  ) +
  geom_point(
    aes(
      shape = ifelse(kandidat == "Merkel" & wahl == "2021", 4, 21),
      col = ifelse(kandidat == "Merkel" & wahl == "2021", "black", "white")),
    size = annotation_size) +
  geom_text(
    data = ~filter(.,
                   wahl %in% c(2005, 2021) & kandidat == "Merkel" |
                   wahl == 1980 |
                   wahl == 1983 & kandidat == "Kohl" |
                   wahl == 1998 & kandidat == "Schröder" |
                   kandidat == "Scholz" |
                   kandidat == "Habeck" |
                   kandidat == "Merz"
                   ),
    aes(label = kandidat),
    family = "Roboto Condensed Medium", size = annotation_size,
    hjust = 0, nudge_x = 0.2
  ) +
  annotate(
    "richtext",
    x = c("1987", "2021", "2025", "2021"), 
    y = c(0.33, -0.55, 0.5, 0.2), 
    label = c(
      "<span style='font-family: Roboto Condensed'>Kohl war 
      bislang<br>der **unbeliebteste<br>erfolgreiche**<br>Kanzlerkandidat</span>",
      "Laschet",
      # "**2025 alle**<br>Kandidaten<br>im Schnitt<br>negativ<br>bewertet",
      "",
      "Baerbock"),
    vjust = c(1, 0.5, 0.5, 0.5),
    hjust = c(0, 1, 0, 1),
    fill = NA, label.size = 0, family = "Roboto Condensed Medium", 
    size = annotation_size, lineheight = 1
  ) +
  annotate(
    GeomCurve,
    x = c("1987"),
    xend = c("1987"),
    y = c(0.31),
    yend = c(0.6),
    curvature = -0.3, linewidth = 0.2
  ) +
  scale_x_discrete(position = "top") +
  scale_y_continuous(labels = scales::label_number(style_positive = "plus")) +
  scale_fill_manual(values = party_pal) +
  scale_shape_identity() +
  scale_color_identity() +
  coord_cartesian(ylim = c(-1, 3), clip = "off") +
  guides(fill = "none") +
  labs(
    title = "2025 erstmals sämtliche Kanzlerkandidaten negativ bewertet",
    subtitle = "Bewertung der Kandidat:innen in der jeweils letzten Politbarometer-Erhebung vor der Bundestagswahl auf einer Skala von -5 bis +5 (2025: Politbarometer Februar II)",
    caption = paste(
      paste(
        "Nicht genannte Kandidaten: ",
       paste(kandidaten_hinweis$wahl_kandidat_label, collapse = ", ")),
      "Daten: Politbarometer (via GESIS & forschungsgruppe.de).
        Visualisierung: Ansgar Wolsing & Thorsten Faas", sep = "<br><br>"
    ),
    x = NULL, y = NULL # "Bewertung"
  ) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.y = element_text(family = "Roboto Condensed SemiBold", size = 12),
    axis.text.x.top = element_text(family = "Roboto Condensed SemiBold", size = 14),
    plot.subtitle = element_textbox(margin = margin(b = 20)),
    plot.margin = margin(t = 6, r = 24, b = 6, l = 6)
  )
```

```{r plot-skalo-3b, fig.width = 7.5, fig.height=7.5}
annotation_size <- 4.25

kandidaten_hinweis <- df_skalo |> 
  filter(!kandidat %in% c("Merkel", "Schröder", "Schmidt", "Kohl", "Merz", "Scholz", 
                          "Baerbock", "Habeck", "Laschet", "Strauß")) |> 
  transmute(wahl_kandidat_label = paste(wahl, kandidat, sep = " "))

df_skalo |> 
  filter(!(wahl == 2021 & kandidat == "Merkel")) |> 
  mutate(wahl_fct = factor(wahl)) |> 
  ggplot(aes(wahl_fct, bewertung, fill = partei)) +
  geom_vline(
    aes(xintercept = wahl_fct), 
    linewidth = 9, color = alpha("grey80", 0.3)) +
  geom_hline(aes(yintercept = 0), linewidth = 0.5) +
  geom_line(
    aes(group = kandidat),
    linetype = "dashed", linewidth = 0.3, col = "grey50"
  ) +
  geom_point(
    aes(
      shape = ifelse(kandidat == "Merkel" & wahl == "2021", 4, 21),
      col = ifelse(kandidat == "Merkel" & wahl == "2021", "black", "white")),
    size = annotation_size) +
  geom_text(
    data = ~filter(.,
                   wahl %in% c(2005, 2021) & kandidat == "Merkel" |
                   wahl == 1980 |
                   wahl == 1983 & kandidat == "Kohl" |
                   wahl == 1998 & kandidat == "Schröder" |
                   kandidat == "Scholz" |
                   kandidat == "Habeck" |
                   kandidat == "Merz"
                   ),
    aes(label = kandidat),
    family = "Roboto Condensed Medium", size = annotation_size,
    hjust = 0, nudge_x = 0.2
  ) +
  annotate(
    "richtext",
    x = c("1987", "2021", "2025", "2021"), 
    y = c(0.33, -0.55, 0.5, 0.2), 
    label = c(
      "<span style='font-family: Roboto Condensed'>Kohl war 
      bislang<br>der **unbeliebteste<br>erfolgreiche**<br>Kanzlerkandidat</span>",
      "Laschet",
      # "**2025 alle**<br>Kandidaten<br>im Schnitt<br>negativ<br>bewertet",
      "",
      "Baerbock"),
    vjust = c(1, 0.5, 0.5, 0.5),
    hjust = c(0, 1, 0, 1),
    fill = NA, label.size = 0, family = "Roboto Condensed Medium", 
    size = annotation_size, lineheight = 1
  ) +
  annotate(
    GeomCurve,
    x = c("1987"),
    xend = c("1987"),
    y = c(0.31),
    yend = c(0.6),
    curvature = -0.3, linewidth = 0.2
  ) +
  scale_x_discrete(position = "top") +
  scale_y_continuous(labels = scales::label_number(style_positive = "plus")) +
  scale_fill_manual(values = party_pal) +
  scale_shape_identity() +
  scale_color_identity() +
  coord_cartesian(ylim = c(-1, 3), clip = "off") +
  guides(fill = "none") +
  labs(
    title = "Noch nie waren Kanzlerkandidaten so unbeliebt",
    subtitle = "Bewertungen im Politbarometer",
    caption = paste(
      paste(
        paste("Nicht genannte Kandidaten:",
       paste(kandidaten_hinweis$wahl_kandidat_label, collapse = ", ")),
       "Bewertung der Kandidat:innen in der jeweils letzten Politbarometer-Erhebung 
       vor der Bundestagswahl auf einer Skala von -5 bis +5 (2025: Politbarometer Februar II)",
      "Daten: Politbarometer (via GESIS & forschungsgruppe.de).
        Visualisierung: Ansgar Wolsing & Thorsten Faas", sep = "<br><br>"
    )),
    x = NULL, y = NULL # "Bewertung"
  ) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.y = element_text(family = "Roboto Condensed SemiBold", size = 12),
    axis.text.x.top = element_text(family = "Roboto Condensed SemiBold", size = 14),
    plot.subtitle = element_textbox(margin = margin(b = 20)),
    plot.margin = margin(t = 6, r = 24, b = 6, l = 6)
  )
```

```{r}
df_skalo |> 
  filter(!(kandidat == "Merkel" & wahl == 2021)) |> 
    select(wahl, kandidat, partei) |> 
    mutate(party_color = party_pal[partei]) |> 
  head()
```

```{r}
df_kandidaten_pro_btw <- df_skalo |> 
  filter(!(kandidat == "Merkel" & wahl == 2021)) |> 
  mutate(
    party_color = party_pal[partei],
    kandidat = ifelse(gewaehlter_kanzler, sprintf("<b>%s</b>", kandidat), kandidat)
    ) |> 
  select(wahl, kandidat, party_color) |> 
  group_by(wahl) |> 
  # summarize(label = str_c(kandidat, collapse = "\n"), .groups = "drop") |>
  summarize(kandidaten_label = str_c(
      sprintf("<span style='font-size: 7pt;color:%s'>\U25B6</span>%s", party_color, kandidat), 
      collapse = "<br>"
    ),
    .groups = "drop") |> 
  mutate(wahl_fct = factor(wahl))
```

```{r plot-skalo-4, fig.width = 9, fig.height=6}

annotation_size <- 4.25

df_skalo |> 
  filter(!(wahl == 2021 & kandidat == "Merkel")) |> 
  mutate(wahl_fct = factor(wahl)) |> 
  ggplot(aes(wahl_fct, bewertung, fill = partei)) +
  geom_vline(
    aes(xintercept = wahl_fct), 
    linewidth = 9, color = alpha("grey80", 0.3)) +
  geom_hline(aes(yintercept = 0), linewidth = 0.5) +
  geom_line(
    aes(group = kandidat),
    linetype = "dashed", linewidth = 0.3, col = "grey50"
  ) +
  geom_point(
    aes(
      shape = ifelse(kandidat == "Merkel" & wahl == "2021", 4, 21),
      col = ifelse(kandidat == "Merkel" & wahl == "2021", "black", "white")),
    size = annotation_size) +
  geom_richtext(
    data = df_kandidaten_pro_btw,
    aes(wahl_fct, 
        # y = 3.4,
        y = ifelse(wahl == 2025, 3.45, 3.4),
        label = kandidaten_label,
        vjust = ifelse(wahl == 2025, 0.6, 0.5)
        ),
    inherit.aes = FALSE,
    family = "Roboto Condensed", size = 4, hjust = 0, # vjust = 0.5, 
    lineheight = 0.85, nudge_x = -0.1, fill = NA, label.size = 0, angle = 45
  ) +
  annotate(
    "richtext",
    x = c("1987"), 
    y = c(0.45), 
    label = c(
      "<span style='font-family: Roboto Condensed'>Kohl war 
      bislang<br>der **unbeliebteste<br>erfolgreiche**<br>Kanzlerkandidat</span>"),
    vjust = c(1),
    hjust = c(0),
    fill = NA, label.size = 0, family = "Roboto Condensed Medium", 
    size = annotation_size, lineheight = 1
  ) +
  annotate(
    GeomCurve,
    x = c("1987"),
    xend = c("1987"),
    y = c(0.31),
    yend = c(0.6),
    curvature = -0.3, linewidth = 0.2
  ) +
  scale_x_discrete(position = "bottom") +
  scale_y_continuous(labels = scales::label_number(style_positive = "plus")) +
  scale_fill_manual(values = party_pal) +
  scale_shape_identity() +
  scale_color_identity() +
  coord_cartesian(ylim = c(-1, 3), clip = "off") +
  guides(fill = "none") +
  labs(
    title = "Noch nie waren Kanzlerkandidaten so unbeliebt",
    subtitle = "Bewertungen im Politbarometer",
    caption = paste(
       "Bewertung der Kandidat:innen in der jeweils letzten Politbarometer-Erhebung 
       vor der Bundestagswahl auf einer Skala von -5 bis +5 (2025: Politbarometer Februar II)",
      "Daten: Politbarometer (via GESIS & forschungsgruppe.de).
        Visualisierung: Ansgar Wolsing & Thorsten Faas", sep = "<br><br>"
    ),
    x = NULL, y = NULL # "Bewertung"
  ) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.y = element_text(family = "Roboto Condensed SemiBold", size = 12),
    axis.text.x = element_text(family = "Roboto Condensed SemiBold", size = 14),
    axis.text.x.top = element_text(family = "Roboto Condensed SemiBold", size = 14),
    plot.subtitle = element_textbox(margin = margin(b = 60)),
    plot.caption = element_textbox(margin = margin(t = 8, b = 6)),
    plot.margin = margin(t = 6, r = 24, b = 6, l = 6)
  )


```

```{r plot-skalo-5, fig.width = 7.2, fig.height=6}

annotation_size <- 4.25

df_skalo |> 
  filter(!(wahl == 2021 & kandidat == "Merkel")) |> 
  mutate(wahl_fct = factor(wahl)) |> 
  ggplot(aes(wahl_fct, bewertung, fill = partei)) +
  geom_vline(
    aes(xintercept = wahl_fct), 
    linewidth = 9, color = alpha("grey80", 0.3)) +
  geom_hline(aes(yintercept = 0), linewidth = 0.5) +
  geom_line(
    aes(group = kandidat),
    linetype = "dashed", linewidth = 0.3, col = "grey50"
  ) +
  geom_point(
    aes(
      shape = ifelse(kandidat == "Merkel" & wahl == "2021", 4, 21),
      col = ifelse(kandidat == "Merkel" & wahl == "2021", "black", "white")),
    size = annotation_size) +
  geom_richtext(
    data = df_kandidaten_pro_btw,
    aes(wahl_fct, 
        y = 3.2,
        label = kandidaten_label,
        # vjust = ifelse(wahl == 2025, 0.6, 0.5)
        vjust = 0.5
        ),
    inherit.aes = FALSE,
    family = "Roboto Condensed", size = 4, hjust = 0, # vjust = 0.5, 
    lineheight = 0.85, nudge_x = 0, fill = NA, label.size = 0, angle = 90
  ) +
  annotate(
    "richtext",
    x = c("1987"), 
    y = c(0.5), 
    label = c(
      "<span style='font-family: Roboto Condensed'>Kohl war 
      bislang<br>der **unbeliebteste<br>erfolgreiche**<br>Kanzlerkandidat</span>"),
    vjust = c(1),
    hjust = c(0),
    fill = NA, label.size = 0, family = "Roboto Condensed Medium", 
    size = annotation_size, lineheight = 1
  ) +
  annotate(
    GeomCurve,
    x = c("1987"),
    xend = c("1987"),
    y = c(0.31),
    yend = c(0.6),
    curvature = -0.3, linewidth = 0.2
  ) +
  scale_x_discrete(position = "bottom") +
  scale_y_continuous(labels = scales::label_number(style_positive = "plus")) +
  scale_fill_manual(values = party_pal) +
  scale_shape_identity() +
  scale_color_identity() +
  coord_cartesian(ylim = c(-1, 3), clip = "off") +
  guides(fill = "none") +
  labs(
    title = "Noch nie waren Kanzlerkandidaten so unbeliebt",
    subtitle = "Bewertungen im Politbarometer",
    caption = paste(
       "Bewertung der Kandidat:innen in der jeweils letzten Politbarometer-Erhebung 
       vor der Bundestagswahl auf einer Skala von -5 bis +5 (2025: Politbarometer Februar II)",
      "Daten: Politbarometer (via GESIS & forschungsgruppe.de).
        Visualisierung: Ansgar Wolsing & Thorsten Faas", sep = "<br><br>"
    ),
    x = NULL, y = NULL # "Bewertung"
  ) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.text.y = element_text(family = "Roboto Condensed SemiBold", size = 12),
    axis.text.x = element_text(family = "Roboto Condensed SemiBold", size = 14),
    axis.text.x.top = element_text(family = "Roboto Condensed SemiBold", size = 14),
    plot.title = element_markdown(size = 18),
    plot.subtitle = element_textbox(size = 14, margin = margin(b = 69)),
    plot.caption = element_textbox(size = 11, margin = margin(t = 8, b = 6)),
    plot.margin = margin(t = 6, r = 24, b = 6, l = 6)
  )
```

```{r plot-skalo-ranking, fig.height=7}

df_skalo |> 
  filter(!(wahl == 2021 & kandidat == "Merkel")) |> 
  mutate(
    kandidat_jahr = sprintf("%s (%d)", kandidat, wahl),
    kandidat_jahr = ifelse(wahl == 2025, paste0("**", kandidat_jahr, "**"), kandidat_jahr),
    kandidat_jahr = fct_reorder(kandidat_jahr, bewertung),
    partei = ifelse(partei %in% c("CDU", "CSU"), "CDU/CSU", partei),
    partei = factor(partei, levels = c("CDU/CSU", "SPD", "Grüne")),
    is_2025 = ifelse(wahl == 2025, 1, 0)) |>
  select(wahl, kandidat_jahr, partei, bewertung, is_2025) |> 
  ggplot(aes(bewertung, kandidat_jahr)) +
  geom_col(
    aes(fill = partei, alpha = ifelse(wahl == 2025, 1, 0.6))
  ) +
  annotate(
    "richtext",
    x = 0.3, y = 3.5,
    label = "Alle Kanzlerkandidaten<br>zur **Bundestagswahl 2025**<br>negativ bewertet",
    family = "Roboto Condensed", hjust = 0, size = 4, lineheight = 0.9,
    fill = "white", label.size = 0
  ) +
  annotate(
    GeomCurve,
    x = 0.27, xend = 0.02,
    y = 3, yend = 3,
    curvature = -0.2,
    arrow = arrow(angle = 20, length = unit(2.5, "mm")),
    linewidth = 0.2
  ) +
  scale_x_continuous(
    position = "top",
    breaks = seq(-5, 5, 0.5),
    labels = scales::label_number(style_positive = "plus")) +
  scale_fill_manual(values = party_pal) +
  scale_alpha_identity() +
  labs(
    title = "Noch nie waren Kanzlerkandidaten so unbeliebt",
    subtitle = "Bewertungen im Politbarometer",
    caption = paste(
       "Bewertung der Kandidat:innen in der jeweils letzten Politbarometer-Erhebung 
       vor der Bundestagswahl auf einer Skala von -5 bis +5 (2025: Politbarometer Februar II)",
      "Daten: Politbarometer (via GESIS & forschungsgruppe.de).
        Visualisierung: Ansgar Wolsing & Thorsten Faas", sep = "<br><br>"
    ),
    x = NULL, y = NULL, fill = "Partei"
  ) +
  theme(
    panel.grid.major.y = element_blank(),
    axis.text.y = element_markdown(hjust = 1),
    plot.caption = element_textbox(margin = margin(t = 8, b = 6)),
    plot.caption.position = "plot",
    legend.position = "inside",
    legend.position.inside = c(0.8, 0.3),
    legend.background = element_rect(color = "white", fill = "white")
  ) 
```

```{r plot-skalo-ranking-patterns, fig.height=7}

library(ggpattern)

df_skalo |> 
  filter(!(wahl == 2021 & kandidat == "Merkel")) |> 
  mutate(
    kandidat_jahr = sprintf("%s (%d)", kandidat, wahl),
    kandidat_jahr = ifelse(wahl == 2025, paste0("**", kandidat_jahr, "**"), kandidat_jahr),
    kandidat_jahr = fct_reorder(kandidat_jahr, bewertung),
    partei = ifelse(partei %in% c("CDU", "CSU"), "CDU/CSU", partei),
    partei = factor(partei, levels = c("CDU/CSU", "SPD", "Grüne")),
    is_2025 = ifelse(wahl == 2025, 1, 0)) |>
  select(wahl, kandidat_jahr, partei, bewertung, is_2025) |> 
  ggplot(aes(bewertung, kandidat_jahr)) +
  # geom_col(
  #   aes(fill = partei, alpha = ifelse(wahl == 2025, 1, 0.6))
  # ) +
  geom_col_pattern(
    aes(fill = partei, 
        pattern = ifelse(is_2025, "stripe", "none")),
    pattern_color = "white",
    pattern_density = 0.01,
    pattern_spacing = 0.015,
    alpha = 0.8
  ) +
  annotate(
    "richtext",
    x = 0.3, y = 3.5,
    label = "Alle Kanzlerkandidaten<br>zur **Bundestagswahl 2025**<br>negativ bewertet",
    family = "Roboto Condensed", hjust = 0, size = 4, lineheight = 0.9,
    fill = "white", label.size = 0
  ) +
  annotate(
    GeomCurve,
    x = 0.27, xend = 0.02,
    y = 3, yend = 3,
    curvature = -0.2,
    arrow = arrow(angle = 20, length = unit(2.5, "mm")),
    linewidth = 0.2
  ) +
  scale_x_continuous(
    position = "top",
    breaks = seq(-5, 5, 0.5),
    labels = scales::label_number(style_positive = "plus", decimal.mark = ",")) +
  scale_fill_manual(values = party_pal) +
  scale_pattern_identity() +
  guides(fill = guide_legend(override.aes = list(pattern = "none"))) +
  labs(
    title = "Noch nie waren Kanzlerkandidaten so unbeliebt",
    subtitle = "Bewertungen im Politbarometer",
    caption = paste(
       "Bewertung der Kandidat:innen in der jeweils letzten Politbarometer-Erhebung 
       vor der Bundestagswahl auf einer Skala von -5 bis +5 (2025: Politbarometer Februar II)",
      "Daten: Politbarometer (via GESIS & forschungsgruppe.de).
        Visualisierung: Ansgar Wolsing & Thorsten Faas", sep = "<br><br>"
    ),
    x = NULL, y = NULL, fill = "Partei"
  ) +
  theme(
    panel.grid.major.y = element_blank(),
    axis.text.y = element_markdown(hjust = 1),
    plot.caption = element_textbox(margin = margin(t = 8, b = 6)),
    plot.caption.position = "plot",
    legend.position = "inside",
    legend.position.inside = c(0.8, 0.3),
    legend.background = element_rect(color = "white", fill = "white")
  ) 

```

## Zuschauerzahlen TV-Duelle

```{r load-data-tvduelle-zuschauer}

df_zuschauer <- read_tsv(here("data", "TV-Duelle", "tv-duelle-quoten.tsv"))
```

```{r plot-zuschauer-tv-duelle}
btw_kandidaten <- tribble(
  ~btw, ~kandidaten,
  2002, "Schröder/Stoiber",
  2005, "Schröder/Merkel",
  2009, "Merkel/Steinmeier",
  2013, "Merkel/Steinbrück",
  2017, "Merkel/Schulz",
  2021, "Laschet/Scholz/Baerbock"
)

df_zuschauer |>
  filter(btw <= 2021) |> 
  inner_join(btw_kandidaten, by = join_by(btw)) |> 
    mutate(
      kandidate_label = ifelse(
         btw %in% 2005:2017,
         str_replace(kandidaten, "/", "/<br>"),
         kandidaten
      ),
    btw_kandidaten_label = sprintf("<b style='font-size:12pt'>%s</b><br>%s", btw, kandidate_label)
    ) |> 
  ggplot(aes(sendungsnummer, zuschauer)) +
  geom_col(
    fill = color_pal[1]
  ) +
  geom_text(
    aes(label = scales::number(zuschauer, accuracy = 0.1, decimal.mark = ",")),
    vjust = 1, nudge_y = -0.5,
    family = "Roboto Condensed SemiBold", col = "white"
  ) +
  geom_hline(aes(yintercept = 0)) +
  facet_grid(cols = vars(btw_kandidaten_label), switch = "x", space = "free_x", scale = "free_x") +
  labs(
    title = "Zuschauerinteresse an den TV-Duellen im Bundestagswahlkampf",
    subtitle = "Zuschauer in Mio.",
    caption = "Daten: Wikipedia, eigene Recherche. Visualisierung: Ansgar Wolsing & Thorsten Faas"
  ) +
  theme(
    axis.text = element_blank(),
    axis.text.x = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    panel.spacing.x = unit(5, "mm"),
    strip.text.x.bottom = element_markdown(
      family = "Roboto Condensed",
      vjust = 1,
      margin = margin(t = 0))
  )
```

#### Zuschauerzahlen ÖRR vs. Privat

```{r plot-zuschauer-tv-duelle-oerr-vs-privat}
df_zuschauer |> 
  filter(btw %in% c(2002, 2021, 2025)) |> 
  mutate(
    sender = str_wrap(sender, 12),
    oerr_privat = case_when(
      str_detect(sender, "ARD|ZDF") ~ "Öffentlich-rechtlich",
      str_detect(sender, "RTL|ntv|Sat\\.1|ProSieben") ~ "Privat"
    )) |> 
  ggplot(aes(sender, zuschauer)) +
  geom_col(
    aes(fill = oerr_privat),
    width = 0.75) +
  geom_text(
    aes(label = scales::number(zuschauer, accuracy = 0.1, decimal.mark = ",")),
    vjust = 1, nudge_y = -0.5,
    family = "Roboto Condensed SemiBold", col = "white"
  ) +
  geom_hline(aes(yintercept = 0)) +
  scale_fill_manual(values = color_pal[c(2, 7)]) +
  facet_grid(cols = vars(btw), switch = "x", space = "free_x", scale = "free_x") +
  labs(
    title = "Zuschauerinteresse an den TV-Duellen im Bundestagswahlkampf",
    subtitle = "Zuschauer in Mio.",
    caption = "Daten: Wikipedia, eigene Recherche. 
    Visualisierung: Ansgar Wolsing & Thorsten Faas",
    fill = NULL
   ) +
   theme(
    legend.position = "top",
    legend.justification = "left",
    axis.text.y = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    panel.spacing.x = unit(5, "mm"),
    plot.caption = element_textbox(margin = margin(t = 6, b = 6)),
    strip.text.x.bottom = element_markdown(
      family = "Roboto Condensed SemiBold",
      vjust = 1,
      margin = margin(t = 0))
  )
  
```
