---
title: "02 Social Media"
format:
  html:
    code-fold: true
    message: false
    warning: false
---

```{r setup}
library(tidyverse)
library(ggtext)
library(gganimate)
library(gt)
library(gtsummary)
library(here)
library(haven)
library(labelled)
library(widyr)

knitr::opts_chunk$set(dev = "ragg_png")

source(here("R", "custom-theme.R"))
theme_set(theme_custom())
```

## Datenquelle

### Bericht

https://library.fes.de/pdf-files/a-p-b/21722.pdf

### Daten einlesen

```{r read-data}
df <- read_stata(here("data", "EPW2024", "ew24AW.dta"))
```

```{r}
colnames(df)
```

```{r}
skimr::skim(df)
```


```{r}
df |> 
  select(geschlecht, alter) |> 
  mutate(across(everything(), haven::as_factor)) |> 
  tbl_summary()
```


```{r}
create_summary_table <- function(x) {
  df <- df |> 
    select(all_of(x)) |> 
    mutate(across(everything(), haven::as_factor))
  colnames(df) <- "var"
  df |> 
    tbl_summary(
      label = list("var" = "Label")
    )
}

vars <- colnames(df)[str_detect(colnames(df), "^v32_")]
var_labels <- unlist(var_label(df[, vars]))

map(vars, create_summary_table) |> 
  tbl_merge(
    tab_spanner = var_labels
  )

```


Welcher Anteil informiert sich ausschließlich über Internet und Social Media?

```{r fig.width=8}

var_labels_v31 <- df |> 
  select(starts_with("v31_")) |> 
  get_variable_labels() |> 
  unlist()

var_labels_v31 <- c("TV o. Mediathek", "Radio o. Audiothek", 
                    "Gedruckte/elektronische Zeitungen", "Beiträge im Internet",
                    "Beiträge in sozialen Medien")
names(var_labels_v31) <- paste0("v31_", 1:5)

val_labels_v31 <- val_labels(df$v31_1) |> 
  unlist()

df |> 
  select(starts_with("v31_")) |> 
  na.omit() |> 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "freq") |> 
  mutate(quelle = var_labels_v31[variable]) |> 
  count(quelle, freq) |> 
  group_by(quelle) |> 
  mutate(share = n / sum(n)) |> 
  ungroup() |> 
  mutate(freq = as.numeric(freq) - 1) |> 
  ggplot(aes(freq, share)) +
  geom_col() + 
  scale_x_reverse() +
  scale_y_continuous(labels = scales::label_percent()) +
  coord_flip() +
  facet_wrap(vars(quelle), nrow = 1) +
  theme(
    strip.text = element_textbox(width = 0.8, hjust = 0)
  )

```

```{r fig.width=9}

var_labels_v31 <- df |> 
  select(starts_with("v31_")) |> 
  get_variable_labels() |> 
  unlist()

var_labels_v31 <- c("TV o. Mediathek", "Radio o. Audiothek", 
                    "Gedruckte/ elektronische Zeitungen", "Beiträge im Internet",
                    "Beiträge in sozialen Medien")
names(var_labels_v31) <- paste0("v31_", 1:5)

df |> 
  select(starts_with("v31_")) |> 
  na.omit() |> 
  pivot_longer(cols = everything(), names_to = "variable", values_to = "freq") |> 
  mutate(quelle = var_labels_v31[variable]) |> 
  mutate(
    quelle = factor(quelle, levels = rev(var_labels_v31)),
    freq = as.numeric(freq) - 1,
    freq_cat = case_when(
      freq == 0 ~ "Nie",
      freq <= 2 ~ "An 1-2 Tagen",
      freq <= 5 ~ "An 3-5 Tagen",
      freq <= 7 ~ "An 6-7 Tagen"
    ),
    freq_cat = factor(freq_cat, 
                      levels = c("Nie", "An 1-2 Tagen", 
                                 "An 3-5 Tagen", "An 6-7 Tagen"))
  ) |> 
  count(quelle, freq_cat) |> 
  group_by(quelle) |> 
  mutate(share = n / sum(n)) |> 
  ungroup() |> 
  ggplot(aes(freq_cat, share)) +
  geom_col(
    aes(fill = quelle %in% c("Beiträge im Internet", "Beiträge in sozialen Medien")),
    width = 0.75) + 
  geom_text(
    aes(
      label = scales::percent(share, accuracy = 1),
      hjust = ifelse(share < 0.25, -0.3, 1.3),
      col = ifelse(share < 0.25, "grey10", "white")),
    family = "Roboto Slab", fontface = "bold"
  ) +
  geom_hline(aes(yintercept = 0)) +
  scale_y_continuous(
    labels = scales::label_percent(), expand = expansion(mult = c(0, 0.05))) +
  scale_color_identity() +
  scale_fill_manual(values = c("FALSE" = color_pal[1], "TRUE" = color_pal[3])) +
  coord_flip() +
  facet_wrap(vars(quelle), nrow = 1) +
  guides(fill = "none") +
  labs(
    x = NULL, 
    y = NULL
  ) +
  theme(
    strip.text = element_textbox(
      size = 11, width = 0.8, height = 0.2, hjust = 0, margin = margin(t = 4, b = 3)),
    panel.grid = element_blank(),
    axis.text.x = element_blank()
  )

```







::: {.callout-note}
Chart noch ungefiltert auf eigene Nutzung
:::

```{r}
var_labels <- df |> 
  select(starts_with("v33_")) |> 
  get_variable_labels() |> 
  unlist()

freq_politikbezug <- df |> 
  select(invcode, starts_with("v33_")) |> 
  mutate(across(starts_with("v33_"), to_factor)) |> 
  pivot_longer(cols = starts_with("v33_"), names_to = "platform", values_to = "freq_politikbezug") |> 
  mutate(platform = var_labels[platform]) |> 
  na.omit() |> 
  count(platform, freq_politikbezug) |> 
  mutate(freq_politikbezug2 = case_when(
    str_sub(freq_politikbezug, 1, 1) %in% c(1, 2) ~ "Selten/nie",
    str_sub(freq_politikbezug, 1, 1) %in% c(4, 5) ~ "Häufig/sehr häufig",
    str_sub(freq_politikbezug, 1, 1) == 3 ~ "Manchmal"
  )) |> 
  add_count(platform, freq_politikbezug2, wt = n, name = "n2") 

# Reihenfolge der Plattformen
platforms_freq_order <- freq_politikbezug |> 
  add_count(platform, wt = n, name = "total_n") |> 
  filter(freq_politikbezug2 == "Häufig/sehr häufig") |> 
  mutate(share = n2 / total_n) |> 
  arrange(share) |> 
  distinct(platform) |> 
  pull()

freq_politikbezug |> 
  filter(platform != "Anderes Netzwerk") |> 
  mutate(platform = factor(platform, levels = platforms_freq_order)) |> 
  ggplot(aes(n, platform, fill = freq_politikbezug, group = freq_politikbezug)) +
  geom_col(position = "fill", color = "white") +
  scale_x_continuous(
    labels = scales::label_percent(), breaks = seq(0, 1, 0.1), position = "top",
    expand = expansion(mult = c(0, 0))) +
  scale_fill_manual(values = c(
    color_pal[4], colorspace::lighten(color_pal[4], 0.3), 
    "grey75", 
    colorspace::lighten(color_pal[2], 0.3), color_pal[2])) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(
    title = sprintf("Auf TikTok Beiträge über Politik gesehen: 40 %% <span style='color:%s'>häufig</span> oder
                    <span style='color:%s'>sehr häufig</span>...",
                    colorspace::lighten(color_pal[2]), color_pal[2]
                    ),
    caption = "Frage: Wenn Sie einmal an die Beiträge denken, die Sie in Ihren sozialen Netzwerken in der vergangenen Woche gesehen haben: Wie häufig hatten diese einen Bezug zu Politikerinnen und Politikern, Parteien oder politischen Themen zur Europawahl?",
    y = NULL
  ) +
  theme(
    legend.position = "top",
    axis.text.y = element_text(hjust = 0),
    panel.grid.major.x = element_line(),
    panel.grid.minor.x = element_line(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()
    )
```

Idee: Marimekko-Chart mit Anzahl der Nutzer auf der y-Achse?

```{r fig.width=8, fig.height=8}
df_marimekko <- freq_politikbezug |> 
  filter(platform != "Anderes Netzwerk") |> 
  mutate(platform = factor(platform, levels = platforms_freq_order)) |> 
  arrange(platform) |> 
  # get the lower and upper boundary for the rectangle for each platform
  add_count(platform, wt = n, name = "n_nutzer_platform") |> 
  nest(data = -c(platform, n_nutzer_platform)) |> 
  mutate(
    n_nutzer_platform_cumul = cumsum(n_nutzer_platform),
    n_nutzer_platform_cumul_lag = lag(n_nutzer_platform_cumul, 1, default = 0),
    pos_label = n_nutzer_platform_cumul_lag + n_nutzer_platform / 2
    ) |> 
  unnest(data) |> 
  # get the position for each segment within a bar (platform)
  group_by(platform) |> 
  arrange(desc(freq_politikbezug), .by_group = TRUE) |> 
  mutate(
    share_politikbezug = n / sum(n),
    share_politikbezug_cumul = cumsum(share_politikbezug),
    share_politikbezug_cumul_lag = lag(share_politikbezug_cumul, 1, default = 0)
  ) |> 
  ungroup() |> 
  select(-c(n, n2, n_nutzer_platform, freq_politikbezug2))

# Labels und Positionen der Labels auf der y-Achse bestimmen
platform_labels_marimekko <- df_marimekko |> 
  distinct(platform, pos_label) |> 
  # Positionen FB und Threads manuell anpassen
  mutate(pos_label = case_when(
    platform == "Threads" ~ pos_label + 300,
    platform == "Facebook" ~ pos_label - 300,
    TRUE ~ pos_label
  ))


df_marimekko|> 
  ggplot(aes(fill = freq_politikbezug)) +
  geom_rect(
    aes(xmin = share_politikbezug_cumul_lag, xmax = share_politikbezug_cumul,
        ymin = n_nutzer_platform_cumul_lag, ymax = n_nutzer_platform_cumul),
    color = "white"
  ) +
  scale_x_continuous(
    labels = scales::label_percent(), breaks = seq(0, 1, 0.1), position = "top",
    expand = expansion(mult = c(0, 0))) +
  scale_y_continuous(
    breaks = platform_labels_marimekko$pos_label,
    labels = platform_labels_marimekko$platform,
    expand = c(0, 0)
  ) +
  scale_fill_manual(values = c(
    color_pal[4], colorspace::lighten(color_pal[4], 0.3), 
    "grey75", 
    colorspace::lighten(color_pal[2], 0.3), color_pal[2])) +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(
    title = sprintf("Auf TikTok Beiträge über Politik gesehen: 40 %% <span style='color:%s'>häufig</span> oder
                    <span style='color:%s'>sehr häufig</span>...",
                    colorspace::lighten(color_pal[2]), color_pal[2]
                    ),
    caption = "Frage: Wenn Sie einmal an die Beiträge denken, die Sie in Ihren sozialen Netzwerken in der vergangenen Woche gesehen haben: Wie häufig hatten diese einen Bezug zu Politikerinnen und Politikern, Parteien oder politischen Themen zur Europawahl?",
    y = NULL
  ) +
  theme(
    legend.position = "top",
    axis.text.y = element_text(hjust = 0),
    panel.grid.major.x = element_line(),
    panel.grid.minor.x = element_line(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank()
    )


```



## Fragestellungen

- Welcher Anteil informiert sich ausschließlich über Internet und Social Media?
- Wahrgenommene Parteien
 


